apiVersion: policy.mcm.ibm.com/v1alpha1
kind: Policy
metadata:
  name: policy-trustedcontainer
  namespace: default
  annotations:
    policy.mcm.ibm.com/standards: NIST-CSF
    policy.mcm.ibm.com/categories: PR.PT Protective Technology
    policy.mcm.ibm.com/controls: PR.PT-3 Least Functionality
spec:
  complianceType: musthave
  remediationAction: inform
  disabled: false
  namespaces:
    exclude: ["kube-*"]
    include: ["default"]
  policy-templates:
    - complianceType: musthave
      objectDefinition:
        apiVersion: policies.ibm.com/v1alpha1
        kind: TrustedContainerPolicy
        metadata:
          name: example-trustedcontainerpolicy
        spec:
          severity: low
          namespaceSelector:
            include: ["default"]
            exclude: ["kube-system"]
          remediationAction: inform
          imageRegistry: quay.io
---
apiVersion: mcm.ibm.com/v1alpha1
kind: PlacementBinding
metadata:
  name: binding-policy-trustedcontainer
  namespace: default
placementRef:
  name: placement-policy-trustedcontainer
  kind: PlacementRule
  apiGroup: apps.open-cluster-management.io
subjects:
- name: policy-trustedcontainer
  kind: Policy
  apiGroup: policy.mcm.ibm.com
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: placement-policy-trustedcontainer
  namespace: default
spec:
  clusterConditions:
  - type: OK
  clusterSelector:
    matchExpressions:
      []
