apiVersion: v1
kind: Pod
metadata:
  name: untrusted-nginx-pod
  namespace: default
spec:
  containers:
  - image: nginx:1.7.9
  # - image: quay.io/ycao56/nginx:latest
    name: nginx
    ports:
    - containerPort: 80