apiVersion: policies.ibm.com/v1alpha1
kind: TrustedContainerPolicy
metadata:
  name: example-samplepolicy
spec:
  severity: low
  namespaceSelector:
    include: ["default"]
    exclude: ["kube-system"]
  remediationAction: inform
  maxClusterRoleBindingGroups: 10
  maxClusterRoleBindingUsers: 10
  maxRoleBindingGroupsPerNamespace: 2
  maxRoleBindingUsersPerNamespace: 2

