apiVersion: policies.ibm.com/v1alpha1
kind: TrustedContainerPolicy
metadata:
  name: example-samplepolicy
spec:
  severity: low
  namespaceSelector:
    include: ["default"]
    exclude: ["kube-system"]
  remediationAction: inform
  imageRegistry: test
