apiVersion: apps/v1
kind: Deployment
metadata:
  name: trusted-container-policy-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      name: trusted-container-policy-controller
  template:
    metadata:
      labels:
        name: trusted-container-policy-controller
    spec:
      serviceAccountName: trusted-container-policy-controller
      containers:
        - name: trusted-container-policy-controller
          # Replace this with the built image name
          image: quay.io/ycao56/trusted-container-policy-controller
          command:
          - trusted-container-policy-controller
          imagePullPolicy: Always
          env:
            - name: OPERATOR_NAME
              value: "trusted-container-policy-controller"
